#! /bin/bash

## clean up script
## run as root

PWD=pwd
LOG_DIR=/var/log
ROOT_UID=0
LINES=50
E_XCD=86
E_NOTROOT=87

if [ "$UID" -ne "$ROOT_UID" ] 
then 
	echo "Must be root to run this script."
	exit $E_NOTROOT
fi

if [ -n $1 ]
then
	line=$1
else
	lines=$LINES
fi

cd $LOG_DIR

if [ $PWD != $LOG_DIR ]
then
	echo "can't change to $LOG_DIR."
	exit $E_XCD
else
	tail -n $LINES messages > mesg.tmp
	mv mesg.tmp messages
	cat /dev/null > wtmp
	echo "logs cleaned up."

fi

exit 0
